sudo: false

language: c
compiler:
  - gcc
  - clang

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "HTQ+Yi+LHr2GxUKEPicR/z5XdjYHIazLLOqCoKmJgQ5FBSyTZS7n6dEsK0wX6WbOyU0Snay5GD8vQkSTEr2ZLXY+E+PT7YXEDq93TuajuYqwuxZix0FgGd1GNuJul7owFp+Z4ZAjt2hb+B8jdEDyQnh93RnV7DGLvJg8nAALcq1E++ngjbGxjyv7tCZZuzmk4PdlkSsPdVzfK/+6BdvBCtsCaSOq4vX93puSs3+BtKNy+NRoPw4v3C0Q1ReQdMWBSVioNQUN+fkgyF2/JS4nQFFFL41Iz9TNCiENqafqGJAaZ3jam95aCLG5ckxHD9snsN3+eF1BqnLCZmguOwFqnmzW7syNmAALWMiCwY3XnNmhc1ShpCXKbGrpv823f5Phko/wfR/LU1zcH1T2zQgDA6XBpL96xgj+u/HUaQthMMs6CXtjJ3TYDtig9BT8y84GyqnCQfT97CGX12L23EzHKNbyKyif+ZPV2RFsRuSAv+yRARZCQARG4KNj3V2oiuqi87YUlgZoqGJXzfsfvdbZFpL0kqn9FEUfKZJPZsbTa6fFyJU0FMzwjX5PZOjZ74fw5dvESL2kaF2YVDGz31HSEibrnXieOSEBoGlGGuerPOnNQUw/c56h3ClR0eUoQmgyjRVpBGKU9lqmJSihEXBE9PMR2D1OQIP+1hKZxkwy5sU="

addons:
  apt:
    packages:
      -libncurses5-dev
      -flex
  coverity_scan:
    project:
      name: "tcadigan/rog-o-matic_XIV"
      description: "My take on Rog-O-Matic XIV"
    notification_email: tylercadigan@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: master

script: make
