sudo: false

language: c
compiler:
  - gcc
  - clang

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "HecjzNgzy62ZsAFFuN/n141CYNRdvaS5eouj5FinlMZGenkZRaTBN4fTs4O4FNnktgJVToLzkQ1Ma2kaHqTbFc0FZ8FoX2H17fhRl1KcgtfOy8eHA+xKQamPWQkg+blmdTyTS6lrds+2PmpKEWiI4vfXa44L8vKu9q2S+k2FIFE="

addons:
  coverity_scan:
    project:
      name: "tcadigan/snobol_III"
      description: "My take on Unix v6 snobol III"
    notification_email: tylercadigan@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: master

script: make