sudo: false

language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libncurses5-dev
  coverity_scan:
    project:
      name: "tcadigan/moria_4.87"
      description: "My take on Moria 4.87"
    notification_email: tylercadigan@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: master

script: make