sudo: false

language: c
compiler:
  - gcc
  - clang
env:
  global:
     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
        #   via the "travis encrypt" command using the project repo's public key
           - secure: "VxC5KSy9eyPANIowObO9WbVl7N1wO3yh2FZ3R5eBBrKnz0TtAxvXxbhsj3I+0hY5V6qLsQCFpUH7wm1iyBLbNaLfV2oKwRepCz7bJ4iYhupL23OfHD6V+dhGfSUNrfeJFc37BskxMwkU2iyHmQ085bG/tJ4e/II1rlCkPbJ9cy44Nvq12ltKloAWHwp/vQsSmyFNV+XYCCGboh9ngpzoYp8r7/PO4IK8OykVwCDsbSnZNAw2kSFiX1Efny86RRybPFLtpHNz+ATuFxQxTLHLkgPVLY76o539sLMkZCVtw2/rSNu6RcCpMheSfQpzT6VJbuObEMQIZH1kae46F2dHF6hCM9IJZ2LaUdftvLCIyYHnjWqK/D6PhMcogyxAdQFTEDlzvjbhn0mMa3NgCujSe/6QIOk1biIs6arYXGfP5+5e+YCuRJEsGzMiHnQ2uzQ787DC6L2PbdAC5eI0d3Pzt1RvPB+zH+QUKEoiSsJrf1akguWjSqWiy2gCrLAgLWWdwYVqRJYt9hK6BLDdN5+XuoP9SFMsc0oTGoPenIvbs6FecY/dBBDP5SkkdB+kNpvYVrK9xdgIjaygfQcDWlCqlj75bJ6Xg+fyARLXTNY55xhLhHpvd7WmjxJzSPFJYumnRd1YDh7X7pbpjb9One/PXT5EAc+oyLsm8CecTMTs14k="
           
addons:
  apt:
    packages:
      libncurses5-dev
  coverity_scan:
    project:
      name: "tcadigan/omega_0.75"
      description: "My take on Omega 0.75"
    notification_email: tylercadigan@gmail.com
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: master
