title: Returning to the digital frontier
email: tylercadigan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A site to hold my thoughts, recollections and explorations
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tcadigan.netlify.com"
github_username:  tcadigan

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  books:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
