#define STR_DROPDTR "Abandon de DTR"
#define STR_CLEANEXIT "Sortie normale de SERSETUP"
#define STR_ATTEMPT "Tentative de connexion en s\202rie, appuyez sur ESC pour annuler."
#define STR_NETABORT "Synchronisation de jeu sur r\202seau annul\202e."
#define STR_DUPLICATE "Cha\214ne id en double. R\202essayez ou v\202rifiez la cha\214ne d'initialistion du modem."
#define STR_MODEMCMD "Commande du modem: "
#define STR_MODEMRESP "R\202ponse du modem: "
#define STR_RESPABORT "R\202ponse du modem annul\202e."
#define STR_CANTREAD "LEcture de MODEM.CFG impossible"
#define STR_DIALING "Composition du num\202ero..."
#define STR_CONNECT "CONNECTION"
#define STR_WAITRING "Attente d'appel..."
#define STR_RING "APPEL"
#define STR_NORESP "Ce fichier de r\202ponse n'existe pas!"
#define STR_DOOMSERIAL "GESTIONNAIRE DE LIAISON SERIE DOOM II v1.4"
#define STR_WARNING \
    "Attention: pas de vecteurs d'interruption NULL ou iret trouv\202s entre 0x60 et 0x66.\n" \
    "Vous pouvez sp\202cifier un vecteur avec le param\212tre -vector 0x<num\202ro>."
#define STR_COMM "Communication avec le vecteur d'interruption 0x%x"
#define STR_RETURNED "Retour de DOOM II"
#define STR_PORTLOOK "Recherche de l'UART sur le port"
#define STR_UART8250 "UART = 8250"
#define STR_UART16550 "UART = 16550"
#define STR_CLEARPEND "Riinitilisation des interruptions en attente.\n"
#define STR_PORTSET "R\351glage du port \340 %lu baud"
