name: Build Your Own Lisp build

on:
  push:
    paths:
    - 'projects/byol/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: A build job
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/general-build
        with:
          path: projects/byol
          language: C