name: Synacor build

on:
  push:
    paths:
    - 'challenges/synacor/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: A build job
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/general-build
        with:
          path: challenges/synacor
          language: C++